### ISSUE TITLE
API não disponível

### ISSUE THREAD

**Issue by cgcdoss** [FelipeMenezesDM/wallet#1]
Olá. Você poderia disponibilizar a API em algum serviço na nuvem (como Heroku, AWS, Azure, etc) para que seja possível testar o front-end?

E assim que disponibilizar, poderia colocar o link da API aqui ou no README.md?

**Comment by FelipeMenezesDM** [comment]
Olá, Cássio.

Obrigado pelo seu interesse em testar a aplicação. O link já está disponível no README.md.

Abs.
